spring:
  application:
    name: mini-marketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017/marketplace
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: marketplace-group
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-issuer.com
jwt:
  secret: your-jwt-secret
jasypt:
  encryptor:
    password: encryption-secret
server:
  port: 8080
graphql:
  servlet:
    mapping: /graphql
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html