server:
  port: 9090  # HTTP if needed, but gRPC on 9090

spring:
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer